### PR TITLE
Question routing changes

### LINKED ISSUE #78: Question pages fail on page refresh
Refreshing one of the question pages (that use dynamic paths) causes the server to throw a 404 error.

### LINKED ISSUE #136: Fix browser refresh css update bug
Bug:
go to individual question page
select an option
refresh browser
-> selected option css class name is reset to notSelectedOption, state is correct
(SSR problem: state is stored in client sessionStorage, nextjs server is not updated?)

### PR DESCRIPTION
**Pull request by Nurou**
- made question page static (removed the [ ] ) -> questions are now transitioned between using the question id as a query string

- added a staticRouting file with methods to enable pushing of query strings to the now static question page since this would otherwise not be possible. NB: the custom useRouter works the same way as the native useRouter
- added missing trailing slash config to prevent crash on refresh

Everything seems to work!

Fixes #136

### CODE REVIEW

File: frontend/components/navigationButtons.jsx [hunk 1]
```diff
@@ -8,8 +8,8 @@ const NavWrapper = styled.nav`
 `
 
 const NavigationButtons = ({ currentQuestionId, surveyLength }) => {
-  const prevQUrl = `/survey/questions/${currentQuestionId - 1}`
-  const nextQUrl = `/survey/questions/${currentQuestionId + 1}`
+  const prevQUrl = `/survey/questions/question/?id=${currentQuestionId - 1}`
+  const nextQUrl = `/survey/questions/question/?id=${currentQuestionId + 1}`
```
Comment (korolainenriikka) [inline frontend/components/navigationButtons.jsx:12]: URLs could be /survey/question/?id=... not /survey/questions/question/... ?

**Review by korolainenriikka — CHANGES_REQUESTED** [review]
Otherwise good and well-commented (++++++++++ for clear single purpose of branch / pull request & small code improvements). Check the URL fix and all's good

File: frontend/components/navigationButtons.jsx (hunk 1 above)
Comment (korolainenriikka) [reply frontend/components/navigationButtons.jsx:12]: BTW: is request changes ok for minor requests like these or more so for bigger issues only?

Comment (lehtoneo) [reply frontend/components/navigationButtons.jsx:12]: I think "/survey/questions/question/?id=x" is logical since there is "/survey/questions/summary/" page as well.

Comment (Nurou) [reply frontend/components/navigationButtons.jsx:12]: > I think "/survey/questions/question/?id=x" is logical since there is "/survey/questions/summary/" page as well.

This was my reasoning

**Review by lehtoneo — APPROVED** [review]

**Review by korolainenriikka — APPROVED** [review]
routes ok
